url: 'https://aprenderdevops.com'
name: aprenderDevOps
description: 'Para profesionales TI interesados en DevOps'

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: '/page/:num/'

exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - vendor
